_wandb:
    value:
        cli_version: 0.26.1
        code_path: code/dqn.py
        e:
            4264y31da4132zi0edsmal0kkxsama3j:
                args:
                    - --env-type
                    - cartpole
                    - --env-name
                    - CartPole-v1
                    - --lr
                    - "3e-4"
                    - --batch-size
                    - "128"
                    - --epsilon-decay
                    - "0.9997"
                    - --epsilon-min
                    - "0.01"
                    - --target-update-frequency
                    - "2000"
                    - --replay-start-size
                    - "5000"
                    - --memory-size
                    - "100000"
                    - --episodes
                    - "3000"
                    - --wandb-run-name
                    - cartpole-V4MSE
                codePath: dqn.py
                codePathLocal: dqn.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "999775268864"
                        used: "312112087040"
                email: gcapitalgt@gmail.com
                executable: C:\Users\g_med\anaconda3\envs\lab5_dl\python.exe
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-79a4aa27-ad26-5680-f6bf-63f410911aa5
                host: Guille
                memory:
                    total: "34029125632"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\g_med\python_new\LAB3\dqn.py
                python: CPython 3.11.15
                root: C:\Users\g_med\python_new\LAB3
                startedAt: "2026-04-30T13:53:20.597397Z"
                writerId: 4264y31da4132zi0edsmal0kkxsama3j
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.11.15
            "5": 0.26.1
            "8":
                - 3
            "12": 0.26.1
            "13": windows-amd64
batch_size:
    value: 128
best_reward_init:
    value: 0
discount_factor:
    value: 0.99
env_name:
    value: CartPole-v1
env_type:
    value: cartpole
episodes:
    value: 3000
epsilon_decay:
    value: 0.9997
epsilon_min:
    value: 0.01
epsilon_start:
    value: 1
frame_stack:
    value: 4
lr:
    value: 0.0003
max_episode_steps:
    value: 10000
memory_size:
    value: 100000
per_alpha:
    value: 0.6
per_beta:
    value: 0.4
replay_start_size:
    value: 5000
save_dir:
    value: ./results
target_update_frequency:
    value: 2000
train_per_step:
    value: 1
use_per:
    value: false
wandb_project:
    value: DLP-Lab5-DQN-CartPole
wandb_run_name:
    value: cartpole-V4MSE
